"""init

Revision ID: ab4f66389853
Revises: 
Create Date: 2025-11-20 14:13:38.984393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4f66389853'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_entries', sa.Column('habit_id', sa.Integer(), nullable=False))
    op.add_column('habit_entries', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('habit_entries', sa.Column('progress_value', sa.Integer(), nullable=False))
    op.add_column('habit_entries', sa.Column('completed', sa.Boolean(), nullable=False))
    op.add_column('habit_entries', sa.Column('entry_metadata', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_habit_entries_date'), 'habit_entries', ['date'], unique=False)
    op.create_index(op.f('ix_habit_entries_habit_id'), 'habit_entries', ['habit_id'], unique=False)
    op.create_foreign_key(None, 'habit_entries', 'habits', ['habit_id'], ['id'])
    op.add_column('habits', sa.Column('title', sa.String(length=50), nullable=False))
    op.add_column('habits', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('habits', sa.Column('type', sa.Enum('DEFAULT', 'COUNTER', 'TIMER', name='habittype'), nullable=False))
    op.add_column('habits', sa.Column('goal_value', sa.Integer(), nullable=False))
    op.add_column('habits', sa.Column('active_on', sa.JSON(), nullable=True))
    op.add_column('habits', sa.Column('settings', sa.JSON(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('habits', 'settings')
    op.drop_column('habits', 'active_on')
    op.drop_column('habits', 'goal_value')
    op.drop_column('habits', 'type')
    op.drop_column('habits', 'description')
    op.drop_column('habits', 'title')
    op.drop_constraint(None, 'habit_entries', type_='foreignkey')
    op.drop_index(op.f('ix_habit_entries_habit_id'), table_name='habit_entries')
    op.drop_index(op.f('ix_habit_entries_date'), table_name='habit_entries')
    op.drop_column('habit_entries', 'entry_metadata')
    op.drop_column('habit_entries', 'completed')
    op.drop_column('habit_entries', 'progress_value')
    op.drop_column('habit_entries', 'date')
    op.drop_column('habit_entries', 'habit_id')
    # ### end Alembic commands ###
