"""added foreign keys

Revision ID: e163d809e741
Revises: ab4f66389853
Create Date: 2025-11-20 21:44:24.658319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e163d809e741'
down_revision: Union[str, Sequence[str], None] = 'ab4f66389853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'habits', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habits', type_='foreignkey')
    op.drop_column('habits', 'author_id')
    # ### end Alembic commands ###
